import type { Metadata } from "next";
import { SITE_URL, business } from "@/config/site";

type PageMetaInput = {
  title: string;
  description: string;
  /** Site-root-relative path, e.g. "/services/irrigation". Use "/" for home. */
  path: string;
  /** Overrides the default generated OG image. */
  image?: { url: string; width: number; height: number; alt: string };
  /** Set true for pages that should not be indexed (e.g. thank-you). */
  noIndex?: boolean;
};

/**
 * Canonical URL for a route.
 *
 * The site root canonicalises to the bare origin with no trailing slash, which
 * is what Next emits and what the sitemap lists — canonical and sitemap must
 * agree exactly or they are conflicting signals.
 */
export function absoluteUrl(path: string): string {
  if (path === "/") return SITE_URL;
  return `${SITE_URL}${path.startsWith("/") ? path : `/${path}`}`;
}

/**
 * Builds page metadata with a self-referencing canonical on the production
 * origin. NEXT_PUBLIC_SITE_URL must be set per environment so a staging build
 * never declares itself canonical.
 */
export function buildMetadata({
  title,
  description,
  path,
  image,
  noIndex,
}: PageMetaInput): Metadata {
  const url = absoluteUrl(path);
  // Branded fallback card, generated by scripts/generate-og.mjs. Pages with
  // strong photography of their own (services, locations, projects) pass an
  // `image` instead. No page is ever left without a share preview — the old
  // site had one on the homepage only, and it was a 2024 screenshot.
  const ogImage = image ?? {
    url: `${SITE_URL}/og/default.jpg`,
    width: 1200,
    height: 630,
    alt: `${business.name} — landscaping, lawn care and snow removal in Spokane, WA`,
  };

  return {
    // Absolute: every page states its full title, so the layout template
    // cannot append the brand name to a title that already contains it.
    title: { absolute: title },
    description,
    alternates: { canonical: url },
    robots: noIndex
      ? { index: false, follow: true }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
    openGraph: {
      type: "website",
      siteName: business.name,
      locale: "en_US",
      url,
      title,
      description,
      images: [ogImage],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [ogImage.url],
    },
  };
}
